# Generated by Django 3.2.6 on 2022-03-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Secretary'), (2, 'Director'), (3, 'Administrator'), (4, 'Staff'), (5, 'Admin')], primary_key=True, serialize=False),
        ),
    ]
