# Generated by Django 3.2.6 on 2022-05-03 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folder',
            options={'ordering': ['title'], 'verbose_name': 'Folder', 'verbose_name_plural': 'Folder Lists'},
        ),
    ]
